build:
  tests-master-firmware:
    image: antoinealb/cpputest
    script:
      - git submodule update --init
      - apt-get update && apt-get install -y cmake python3-pip
      - pip3 install cvra-packager
      - cd master-firmware
      - packager
      - mkdir build && pushd build
      - cmake ..
      - make check
      - popd
